artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/krishnaik06/datasets/blob/main/winequality-data.zip
  local_data_file: artifacts/data_ingestion/winequality-data.zip
  unzip_dir: artifacts/data_ingestion/winequality-data.zip

data_validation:
  root_dir: artifacts/data_validation
  unzipped_data: artifacts/data_ingestion/winequality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt